## Elasticsearch setup

## DEV

elastic_password_dev_manual:
  extends:
    - .elastic_password_template
    - .variables_dev
    - .rules_dev_manual

## TEST

elastic_password_test_manual:
  extends:
    - .elastic_password_template
    - .variables_test
    - .rules_test_manual

## PROD

elastic_password_prod_manual:
  extends:
    - .elastic_password_template
    - .variables_prod
    - .rules_prod_manual