deploy_heartbeat_dev_manual:
  extends:
    - .deploy_heartbeat_template
    - .variables_dev
    - .rules_dev_manual

deploy_heartbeat_staging_manual:
  extends:
    - .deploy_heartbeat_template
    - .variables_staging
    - .rules_staging_manual