##### Development Branch

deploy_logstash_dev_manual:
  extends:
    - .deploy_logstash_template
    - .variables_dev
    - .rules_dev_manual

deploy_logstash_dev_external:
  extends:
    - .deploy_logstash_files_template
    - .variables_dev
    - .rules_dev_external

restart_logstash_dev:
  extends:
    - .deploy_logstash_template
    - .variables_dev
    - .rules_dev_auto_changes

logstash_test_dev:
  extends:
    - .log_template
    - .variables_dev
    - .rules_dev_auto

#####  Test Branch

restart_logstash_test:
  extends:
    - .deploy_logstash_template
    - .variables_test
    - .rules_test_auto_changes

deploy_logstash_test_manual:
  extends:
    - .deploy_logstash_template
    - .variables_test
    - .rules_test_manual
