## Restart ELK Stack Scripts

## DEV

restart_stack_dev_manual:
  extends:
    - .restart_stack_template_dev_only
    - .variables_dev
    - .rules_dev_manual

## TEST

restart_stack_test_manual:
  extends:
    - .restart_stack_template
    - .variables_test
    - .rules_test_manual

## PROD
restart_stack_prod_manual:
  extends:
    - .restart_stack_template
    - .variables_prod
    - .rules_prod_manual