- name: role and user migration Deploy
  hosts: node1
  tasks:
    - name: Ensure maven is installed
      apt: name=maven state=present
      become: yes
    
    - name: Ensures /etc/migration dir exists
      file: path=/etc/migration state=directory
      become: yes
    
    - name: Copy role user folder
      copy:
        src: ../migration/
        dest: /etc/migration
      become: yes