- name: Heartbeat Installation
  hosts: node3
  tasks:
    - name: Ensure heartbeat is at the "{{ lookup('ENV','ELK_VERSION') }}" version
      apt: name=heartbeat-elastic={{ lookup('ENV','ELK_VERSION') }} state=present
      become: yes
    - name: Ensures /etc/heartbeat/security dir exists
      file: path=/etc/heartbeat/security state=directory
      become: yes
    - name: Copy security folder 
      copy:
        src: security
        dest: /etc/heartbeat/
      become: yes
    - name: Copy heartbeat config yml
      copy:
        src: heartbeat.yml
        dest: /etc/heartbeat
      become: yes
    - name: Add Block
      blockinfile:
        dest: /etc/heartbeat/heartbeat.yml
        block: |
          http.enabled: true
          monitoring.enabled: false # legacy monitoring off
          http.port: 5067
          http.host: {{ inventory_hostname }} 
    - name: Copy monitors.d folder
      synchronize:
        src: monitors.d
        dest: /etc/heartbeat
        delete: yes
        dirs: yes
      become: yes
    - name: Update permissions for monitors.d folder
      command: chown root /etc/heartbeat/monitors.d
      args:
        warn: false
      become: yes
    - name: Update permissions for monitors
      shell: chown root /etc/heartbeat/monitors.d/*
      args:
        warn: false
      become: yes
    - name: Update write permissions for monitors
      shell: chmod go-w /etc/heartbeat/monitors.d/*
      args:
        warn: false
      become: yes
    - name: stop heartbeat
      service:
          name: heartbeat-elastic
          state: stopped
      become: yes  
    - name: start heartbeat
      service:
          name: heartbeat-elastic
          state: started
      become: yes 