- name: Heartbeat Installation
  hosts: node3
  tasks:
    - name: Ensure heartbeat is at the "{{ lookup('ENV','elk_version') }}" version
      apt: name=heartbeat-elastic={{ lookup('ENV','elk_version') }} state=present
      become: yes
    - name: Copy heartbeat config yml
      copy:
        src: heartbeat.yml
        dest: /etc/heartbeat
      become: yes
    - name: Copy monitors.d folder
      copy:
        src: monitors.d
        dest: /etc/heartbeat
      become: yes
    - name: stop heartbeat
      service:
          name: heartbeat-elastic
          state: stopped
      become: yes  
    - name: start heartbeat
      service:
          name: heartbeat-elastic
          state: started
      become: yes 
