- name: FileBeat Instalation
  hosts: all
  tasks:
    - name: Ensure FileBeat is at the "{{ lookup('ENV','ELK_VERSION') }}" version
      apt: name=filebeat={{ lookup('ENV','ELK_VERSION') }} state=present
      become: yes
    - name: Copy security folder 
      copy:
        src: security
        dest: /etc/filebeat/
        force: yes
      become: yes
    - name: Copy filebeat config yml
      copy:
        src: filebeat.yml
        dest: /etc/filebeat
        force: yes
      become: yes
    # - name: Add Block
    #   blockinfile:
    #     dest: /etc/filebeat/filebeat.yml
    #     block: |
    #       http.enabled: true
    #       monitoring.enabled: false # legacy monitoring off
    #       http.port: 5066
    #       http.host: node1
    - name: Copy modules.d folder
      synchronize:
        src: modules.d
        dest: /etc/filebeat/modules.d
        delete: yes
        dirs: yes
      become: yes
    - name: start filebeat
      service:
          name: filebeat
          state: restarted
      become: yes