stages:
  - base_setup
  - elastic_deploy
  - kibana_deploy
  - logstash_deploy

base_setup:
  stage: base_setup
  when: manual
  tags: 
    - uat144
  script: 
         - echo 'base_setup start'
         - bash -x script-uat.sh
         - echo 'base_setup end'
  

elastic_deploy:
  stage: elastic_deploy
  when: manual
  tags: 
    - uat144
  script: 
         - echo 'elastic_deploy start'
         - ansible-playbook -i host elk-uat.yml
         - echo 'elastic_deploy end'

kibana_deploy:
  stage: kibana_deploy
  when: manual
  tags: 
    - uat144
  script: 
         - echo 'kibana_deploy start'
         - ansible-playbook -i host kibana-uat.yml
         - echo 'kibana_deploy end'

logstash_deploy:
  stage: logstash_deploy
  when: manual
  tags:
    - uat144
  script:
         - echo 'logstash_deploy start'
         - echo 'logstash_deploy end'
 