include:
  - local: '.variables.yml'
stages:
  - base_setup
  - elastic_deploy
  - kibana_deploy
  - logstash_deploy

base_setup:
  stage: base_setup
  when: manual
  tags: 
    - staging
  script: 
         - echo 'base_setup start'
         - bash -x scripts/general/script.sh $NODE1 $NODE2 $NODE3 $ENV
         - echo 'base_setup end'
  

elastic_deploy:
  stage: elastic_deploy
  when: manual
  tags: 
    - staging
  script: 
         - echo 'elastic_deploy start'
         - ansible-playbook -i host elastic/general/elk.yml
         - echo 'elastic_deploy end'

kibana_deploy:
  stage: kibana_deploy
  when: manual
  tags: 
    - staging
  script: 
         - echo 'kibana_deploy start'
         - ansible-playbook -i host kibana/general/kibana.yml
         - echo 'kibana_deploy end'

logstash_deploy:
  stage: logstash_deploy
  when: manual
  tags:
    - staging
  script:
         - 'sed -i s/ENV/$ENV/g $CI_PROJECT_DIR/logstash/general/config/file_input.conf $CI_PROJECT_DIR/logstash/general/config/master-data.conf $CI_PROJECT_DIR/logstash/general/config/target.conf'
         - echo 'logstash_deploy start'
         - ansible-playbook -i host logstash/general/logstash.yml
         - echo 'logstash_deploy end'
