stages:
  - elastic_deploy
  - kibana_deploy
  - logstash_deploy

elastic_deploy:
  stage: elastic_deploy
  when: manual
  tags: 
    - uat140
  script: 
         - echo 'elastic_deploy start'
         - script.sh
         - echo 'elastic_deploy end'
  

kibana_deploy:
  stage: kibana_deploy
  when: manual
  tags: 
    - uat140
  script: 
         - echo 'kibana_deploy start'
         - echo 'kibana_deploy end'

logstash_deploy:
  stage: logstash_deploy
  when: manual
  tags:
    - uat140
  script:
         - echo 'logstash_deploy start'
         - echo 'logstash_deploy end'
 