stages:
  - kube_deploy_manual
  - elk_deploy

kube_deploy:
  stage: kube_deploy_manual
  when: manual
  tags: 
    - test123
  script: 
         - echo 'kube_deploy start'
         - cp kube-setup/node-k8s.sh /root/
         - cd kube-setup
         - sh master-k8s.sh
         - echo 'kube_deploy end'
  

elk_config:
  stage: elk_deploy
  when: manual
  tags: 
    - test123
  script: 
         - echo 'elk-config start'
         - cd elk-config
         - kubectl apply -f storage-class.yaml
         - kubectl apply -f pv.yaml
         - kubectl apply -f pv-1.yaml
         - kubectl apply -f pv-2.yaml
         - kubectl apply -f elasticsearch.yaml
         - kubectl apply -f kibana.yaml
         - kubectl apply -f ls.yaml
         - kubectl apply -f ls-configmap.yml
         - echo 'elk-config end'