stages:
  - deploy
  - deploy_manual

kube_deploy:
  stage: deploy_manual
  tags: 
    - dev
    - master
  script: 
         - echo 'kube_deploy start'
         - cd kube-setup
         - sh master-k8s.sh
         - echo 'kube_deploy end'

elk_config:
  stage: deploy
  tags: 
    - dev
    - master
  script: 
         - echo 'elk-config start'
         - cd elk-config
         - kubectl apply -f storage-class.yaml
         - kubectl apply -f pv.yaml
         - kubectl apply -f pv-1.yaml
         - kubectl apply -f pv-2.yaml
         - kubectl apply -f elasticsearch.yaml
         - kubectl apply -f ls-configmap.yml
         - echo 'elk-config end'