include:
  - local: '.variables.yml'
stages:
  - base_setup
  - elastic_deploy
  - kibana_deploy
  - logstash_deploy
  - heartbeat_deploy
  - test

base_setup:
  stage: base_setup
  when: manual
  environment:
    name: development
  tags: 
    - dev
  script: 
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'base_setup start'
         - bash -x scripts/general/script.sh $NODE1 $NODE2 $NODE3 $ENV
         - echo 'base_setup end'
  

elastic_deploy:
  stage: elastic_deploy
  when: manual
  environment:
    name: development
  tags: 
    - dev
  script: 
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'elastic_deploy start'
         - ansible-playbook -i host elastic/general/elk.yml
         - echo 'elastic_deploy end'

kibana_deploy:
  stage: kibana_deploy
  when: manual
  environment:
    name: development
  tags: 
    - dev
  script: 
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'kibana_deploy start'
         - ansible-playbook -i host kibana/general/kibana.yml
         - echo 'kibana_deploy end'

logstash_deploy:
  stage: logstash_deploy
  when: manual
  environment:
    name: development
  tags:
    - dev
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         #- 'sed -i s/ENV/$ENV/g $CI_PROJECT_DIR/logstash/general/config/logstash.yml $CI_PROJECT_DIR/logstash/general/config/pipelines/file_input.conf $CI_PROJECT_DIR/logstash/general/config/pipelines/master-data.conf $CI_PROJECT_DIR/logstash/general/config/pipelines/target.conf'
         - echo 'logstash_deploy start'
         - ansible-playbook -i host logstash/general/logstash.yml
         - echo 'logstash_deploy end'

heartbeat_deploy:
  stage: heartbeat_deploy
  when: manual
  environment:
    name: development
  tags: 
    - dev
  script: 
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'heartbeat_deploy start'
         - ansible-playbook -i host heartbeat/heartbeat-setup.yml
         - echo 'heartbeat_deploy end'