include:
  - local: '.variables.yml'
stages:
  - base_setup
  - elastic_deploy
  - kibana_deploy
  - logstash_deploy

base_setup:
  stage: base_setup
  when: manual
  tags: 
    - uat144
  script: 
         - echo 'base_setup start'
         - bash -x script-$ENV.sh $NODE1 $NODE2 $NODE3 $ENV
         - echo 'base_setup end'
  

elastic_deploy:
  stage: elastic_deploy
  when: manual
  tags: 
    - uat144
  script: 
         - echo 'elastic_deploy start'
         - ansible-playbook -i host elk-$ENV.yml
         - echo 'elastic_deploy end'

kibana_deploy:
  stage: kibana_deploy
  when: manual
  tags: 
    - uat144
  script: 
         - echo 'kibana_deploy start'
         - ansible-playbook -i host kibana-$ENV.yml
         - echo 'kibana_deploy end'

logstash_deploy:
  stage: logstash_deploy
  when: manual
  tags:
    - uat144
  script:
         - 'sed -i s/ENV/$ENV/g $CI_PROJECT_DIR/file_input.conf $CI_PROJECT_DIR/master-data.conf $CI_PROJECT_DIR/target.conf'
         - echo 'logstash_deploy start'
         - ansible-playbook -i host logstash.yml
         - echo 'logstash_deploy end'
