- hosts: node1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_enable_xpack: true
    es_data_dirs:
      - "/data/elasticsearch/data"
    es_log_dir: "/data/elasticsearch/logs"
    es_path_repo: "/data/elasticsearch/backup"
    es_java_install: true
    es_heap_size: "1g"
    es_ssl_certificate_authority: /tmp/elk/dev/ca/ca.crt
    es_ssl_key: /tmp/elk/dev/node1/node1.key
    es_ssl_certificate: /tmp/elk/dev/node1/node1.crt
    es_enable_http_ssl: true
    es_enable_auto_ssl_configuration: true
    es_api_basic_auth_username: "elastic"
    es_api_basic_auth_password: "Elastic@123"
    es_enable_transport_ssl: true 
    es_enable_auto_ssl_configuration: true
    es_xpack_features: []
    es_config:
      cluster.name: "elk-cluster"
      cluster.initial_master_nodes: "node1"
      discovery.seed_hosts: "node1.elastic.dev.net , node2.elastic.dev.net , node3.elastic.dev.net"
      http.port: 9200
      node.data: true
      node.master: true
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
     - plugin: ingest-attachment

- hosts: node2
  roles:
    - role: elastic.elasticsearch
  vars:
    es_enable_xpack: true
    es_data_dirs:
      - "/data/elasticsearch/data"
    es_log_dir: "/data/elasticsearch/logs"
    es_path_repo: "/data/elasticsearch/backup"
    es_java_install: true
    es_heap_size: "1g"
    es_ssl_certificate_authority: /tmp/elk/dev/ca/ca.crt
    es_ssl_key: /tmp/elk/dev/node2/node2.key
    es_ssl_certificate: /tmp/elk/dev/node2/node2.crt
    es_enable_http_ssl: true
    es_enable_auto_ssl_configuration: true
    es_api_basic_auth_username: "elastic"
    es_api_basic_auth_password: "Elastic@123"
    es_enable_transport_ssl: true 
    es_enable_auto_ssl_configuration: true
    es_xpack_features: []
    es_config:
      cluster.name: "elk-cluster"
      cluster.initial_master_nodes: "node1"
      discovery.seed_hosts: "node1.elastic.dev.net , node2.elastic.dev.net , node3.elastic.dev.net"
      http.port: 9200
      node.data: true
      node.master: true
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
     - plugin: ingest-attachment

- hosts: node3
  roles:
    - role: elastic.elasticsearch
  vars:
    es_enable_xpack: true
    es_data_dirs:
      - "/data/elasticsearch/data"
    es_log_dir: "/data/elasticsearch/logs"
    es_path_repo: "/data/elasticsearch/backup"
    es_java_install: true
    es_heap_size: "1g"
    es_ssl_certificate_authority: /tmp/elk/dev/ca/ca.crt
    es_ssl_key: /tmp/elk/dev/node3/node3.key
    es_ssl_certificate: /tmp/elk/dev/node3/node3.crt
    es_enable_http_ssl: true
    es_enable_auto_ssl_configuration: true
    es_api_basic_auth_username: "elastic"
    es_api_basic_auth_password: "Elastic@123"
    es_enable_transport_ssl: true 
    es_enable_auto_ssl_configuration: true
    es_xpack_features: []
    es_config:
      cluster.name: "elk-cluster"
      cluster.initial_master_nodes: "node1"
      discovery.seed_hosts: "node1.elastic.dev.net , node2.elastic.dev.net , node3.elastic.dev.net"
      http.port: 9200
      node.data: true
      node.master: true
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
     - plugin: ingest-attachment

