- name: Kibana Instalation
  hosts: node1
  tasks:
    - name: Ensure logstash is at the latest version
      apt: name=logstash state=latest
      become: yes
    - name: start logstash
      service:
          name: logstash
          state: started
      become: yes
