## Base setup templates 

.base_setup_template:
  stage: base_setup
  script:
         - export
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'BASE SETUP START'
         - bash -x base_setup/base_setup.sh $NODE1 $NODE2 $NODE3 $ENV
         - echo 'BASE SETUP END'

.cron_clear_logs_template:
  stage: base_setup
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Setup Clear Logs Cron Job'
         # Node1
         - cp base_setup/clear_logs.sh /etc/cron.daily/clear_logs.sh
         - chmod +x /etc/cron.daily/clear_logs.sh

         # Node2
         - scp /data/clear_logs.sh root@node2:/etc/cron.daily/clear_logs.sh
         - ssh node2 chmod +x /etc/cron.daily/clear_logs.sh

         # Node3
         - scp /data/clear_logs.sh root@node3:/etc/cron.daily/clear_logs.sh
         - node3 chmod +x /etc/cron.daily/clear_logs.sh