## Elasticsearch templates

.elastic_password_template:
  stage: deploy_elk_stack
  script:
         - export
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Elastic Password SETUP START'
         - ansible-playbook -i host elasticsearch/elastic-password.yml
         - echo 'Elastic Password SETUP END'