## Elasticsearch templates

.elasticsearch_setup_template:
  stage: deploy_elk_stack
  script:
         - export
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'ELASTICSEARCH SETUP START'
         - ansible-playbook -i host elasticsearch/elasticsearch-setup.yml
         - cp elasticsearch/role_mapping.yml /etc/elasticsearch/role_mapping.yml
         - service elasticsearch restart
         - echo 'ELASTICSEARCH SETUP END'