## Logs templates

.log_template:
  stage: logs
  script:
         - export
         # ELK Cluster Logs
         - scp node1:/data/elasticsearch/logs/ELK-$ENV-Cluster.log elk-cluster-node1.log      
         - scp node2:/data/elasticsearch/logs/ELK-$ENV-Cluster.log elk-cluster-node2.log
         - scp node3:/data/elasticsearch/logs/ELK-$ENV-Cluster.log elk-cluster-node3.log
         # Logstash Logs
         - scp node3:/var/log/logstash/logstash-plain.log logstash-node3.log
         - ssh node3 tail -n 50 /var/log/logstash/logstash-plain.log
  artifacts:
    paths:
      - logstash-node3.log
      - elk-cluster-node1.log
      - elk-cluster-node2.log
      - elk-cluster-node3.log
    expire_in: 1 week
