## Restark ELK Stack templates

.restart_stack_template:
  stage: restart_stack
  script:
         - export

         ## Node3
         - ssh node3 service logstash restart
         - service metricbeat restart
         - service filebeat restart
         - service heartbeat-elastic restart
         - service elasticsearch restart
         
         ## Node2
         - ssh node2 service metricbeat restart
         - service filebeat restart
         - service kibana restart
         - service elasticsearch restart

         ## Node1
         - ssh node1 service metricbeat restart
         - service filebeat restart
         - service kibana restart
         - service elasticsearch restart