## Restark ELK Stack templates

.restart_stack_template:
  stage: restart_stack
  script:
         - export

         ## Elastisearch

         - ssh node1 service elasticsearch restart
         - ssh node2 service elasticsearch restart
         - ssh node3 service elasticsearch restart

         ## Kibana

         - ssh node1 service kibana restart
         - ssh node2 service kibana restart

         ## Logstash

         - ssh node3 service logstash restart

         ## Metricbeat

         - ssh node1 service metricbeat restart
         - ssh node2 service metricbeat restart
         - ssh node3 service metricbeat restart

         ## Filebeat

         - ssh node1 service filebeat restart
         - ssh node2 service filebeat restart
         - ssh node3 service filebeat restart

         ## Heartbeat

         - ssh node3 service heartbeat-elastic restart