## start Module templates


## start Logstash
.start_logtash_template:
  stage: start_module
  script:
         - export
         - ssh node3 service logstash start
         - ssh node3 service logstash status

## start Heartbeat
.start_heartbeat_template:
  stage: start_module
  script:
         - export

         ## Node3
         - ssh node3 service heartbeat-elastic start
         - ssh node3 service heartbeat-elastic status
         
        #  ## Node2
        #  - ssh node2 service heartbeat-elastic start
        #  - ssh node2 service heartbeat-elastic status

        #  ## Node1
        #  - ssh node1 service heartbeat-elastic start
        #  - ssh node1 service heartbeat-elastic status

## start Metricbeat
.start_metricbeat_template:
  stage: start_module
  script:
         - export

         ## Node3
         - ssh node3 service metricbeat start
         - ssh node3 service metricbeat status
         
         ## Node2
         - ssh node2 service metricbeat start
         - ssh node2 service metricbeat status

         ## Node1
         - ssh node1 service metricbeat start
         - ssh node1 service metricbeat status

## start Filebeat
.start_filebeat_template:
  stage: start_module
  script:
         - export

         ## Node3
         - ssh node3 service filebeat start
         - ssh node3 service filebeat status
         
         ## Node2
         - ssh node2 service filebeat start
         - ssh node2 service filebeat status

         ## Node1
         - ssh node1 service filebeat start
         - ssh node1 service filebeat status

## start Kibana
.start_kibana_template:
  stage: start_module
  script:
         - export

         ## Node2
         - ssh node2 service kibana start
         - ssh node2 service kibana status

         ## Node1
         - ssh node1 service kibana start
         - ssh node1 service kibana status

## start Elasticsearch
.start_elasticsearch_template:
  stage: start_module
  script:
         - export

         ## Node3
         - ssh node3 service elasticsearch start
         - ssh node3 service elasticsearch status

         ## Node2
         - ssh node2 service elasticsearch start
         - ssh node2 service elasticsearch status

         ## Node1
         - ssh node1 service elasticsearch start
         - ssh node1 service elasticsearch status