- name: Kibana Instalation
  hosts: node1
  tasks:
    - name: Ensure kibana is at the 7.10.1 version
      apt: name=kibana=7.10.1 state=present
      become: yes
    - name: Ensures /etc/kibana/config/certs dir exists
      file: path=/etc/kibana/config/certs state=directory
      become: yes
    - name: Copy ca file 
      copy:
        src: security/ca/ca.crt
        dest: /etc/kibana/config/certs/ca.crt
      become: yes
    - name: Copy config file 
      copy:
        src: "config/{{ lookup('ENV','ENV') }}/kibana-conf-{{ lookup('ENV','ENV') }}.yml"
        dest: /etc/kibana/kibana.yml
        force: yes
      become: yes
    - name: add TLS
      blockinfile:
        dest: /etc/kibana/kibana.yml
        block: |
          'xpack.security.enabled: true'
          'xpack.fleet.agents.tlsCheckDisabled: true'
          'xpack.security.encryptionKey: "BDHcisme3231234msid8493029384930281hc"'
          'xpack.encryptedSavedObjects.encryptionKey: "BDHcisme3231234msid8493029384930281hc"'
          'test auto'
      become: yes
    - name: start kibana
      service:
          name: kibana
          state: restarted
      become: yes  

- name: Kibana Instalation on node2
  hosts: node2
  tasks:
    - name: Ensure kibana is at the 7.10.1 version
      apt: name=kibana=7.10.1 state=present
      become: yes
    - name: Ensures /etc/kibana/config/certs dir exists
      file: path=/etc/kibana/config/certs state=directory
      become: yes
    - name: Copy ca file 
      copy:
        src: security/ca/ca.crt
        dest: /etc/kibana/config/certs/ca.crt
      become: yes
    - name: Copy config file 
      copy:
        src: "config/{{ lookup('ENV','ENV') }}/kibana-conf-{{ lookup('ENV','ENV') }}.yml"
        dest: /etc/kibana/kibana.yml
        force: yes
      become: yes
    - name: add TLS
      blockinfile:
        dest: /etc/kibana/kibana.yml
        block: |
          'xpack.security.enabled: true'
          'xpack.fleet.agents.tlsCheckDisabled: true'
          'xpack.security.encryptionKey: "BDHcisme3231234msid8493029384930281hc"'
          'xpack.encryptedSavedObjects.encryptionKey: "BDHcisme3231234msid8493029384930281hc"'
          'test auto'
      become: yes
    - name: start kibana
      service:
          name: kibana
          state: restarted
      become: yes  