- name: Kibana Instalation
  hosts: node1
  tasks:
    - name: Ensure kibana is at the "{{ lookup('ENV','elk_version') }}" version
      apt: name=kibana={{ lookup('ENV','elk_version') }} state=present
      become: yes
    - name: Ensures /etc/kibana/config/certs dir exists
      file: path=/etc/kibana/config/certs state=directory
      become: yes
    - name: Copy certs folder 
      copy:
        src: security
        dest: /etc/kibana/config/certs
      become: yes
    - name: Copy config file 
      copy:
        src: kibana.yml
        dest: /etc/kibana/kibana.yml
        force: yes
      become: yes
    - name: start kibana
      service:
          name: kibana
          state: restarted
      become: yes  

- name: Kibana Instalation on node2
  hosts: node2
  tasks:
    - name: Ensure kibana is at the "{{ lookup('ENV','elk_version') }}" version
      apt: name=kibana={{ lookup('ENV','elk_version') }} state=present
      become: yes
    - name: Ensures /etc/kibana/config/certs dir exists
      file: path=/etc/kibana/config/certs state=directory
      become: yes
    - name: Copy certs folder 
      copy:
        src: security
        dest: /etc/kibana/config/certs
      become: yes
    - name: Copy config file 
      copy:
        src: kibana.yml
        dest: /etc/kibana/kibana.yml
        force: yes
      become: yes
    - name: start kibana
      service:
          name: kibana
          state: restarted
      become: yes  