- name: MetricBeat Instalation
  hosts: all
  tasks:
    - name: Ensure metricbeat is at the "{{ lookup('ENV','ELK_VERSION') }}" version
      apt: name=metricbeat={{ lookup('ENV','ELK_VERSION') }} state=present
      become: yes
    - name: Copy security folder 
      copy:
        src: security
        dest: /etc/metricbeat/
      become: yes
    - name: Copy metricbeat config yml
      copy:
        src: metricbeat.yml
        dest: /etc/metricbeat
      become: yes
    - name: Add Block
      blockinfile:
        dest: /etc/metricbeat/metricbeat.yml
        block: |
          http.enabled: true
          monitoring.enabled: false # legacy monitoring off
          http.port: 5066
          http.host: {{ inventory_hostname }} 
      become: yes
    - name: Copy modules.d folder
      copy:
        src: modules.d
        dest: /etc/metricbeat
      become: yes
    - name: start metricbeat
      service:
          name: metricbeat
          state: restarted
      become: yes