- name: Elasticsearch Password
  hosts: all
  tasks:

    - name: stop elasticsearch
      service:
          name: elasticsearch
          state: stopped
      become: yes

    - name: Set Temp Bootstrap Password
      when: inventory_hostname in groups['node1']
      #command: printf """{{ lookup('ENV','BOOTSTRAP_PASSWORD') }}""" | /usr/share/elasticsearch/bin/elasticsearch-keystore add -x "bootstrap.password"
      shell: printf "TEMP_bootstrap_PASSWORD@PROD" | /usr/share/elasticsearch/bin/elasticsearch-keystore add -x "bootstrap.password"
      become: yes

    - name: start elasticsearch
      service:
          name: elasticsearch
          state: started
      become: yes

    - name: Set Elastic Password
      when: inventory_hostname in groups['node1']
      uri:
        validate_certs: false
        url: https://{{ lookup('ENV','NODE1') }}:9200/_xpack/security/user/elastic/_password
        user: elastic
        password: "{{ lookup('ENV','BOOTSTRAP_PASSWORD') }}"
        method: PUT
        body_format: json
        body: '{ "password":"{{ lookup(''ENV'',''ELASTICSEARCH_PASSWORD'') }}" }'
        headers:
          Content-Type: application/json
      become: yes