- name: Elasticsearch Installation
  hosts: all
  tasks:

    - name: Import Elasticsearch PGP Key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      become: yes
    
    - name: Install apt-transport-https
      apt: name=apt-transport-https state=present
      become: yes

    - name: Add ELK Repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
      become: yes
    
    - name: APT-GET Update
      apt: update_cache=yes
      become: yes

    - name: Ensure elasticsearch is at the "{{ lookup('ENV','ELK_VERSION') }}" version
      apt: name=elasticsearch={{ lookup('ENV','ELK_VERSION') }} state=present
      become: yes
      
    - name: Ensures /etc/elasticsearch/security dir exists
      file: path=/etc/elasticsearch/security state=directory
      become: yes

    - name: Copy security folder 
      copy:
        src: security
        dest: /etc/elasticsearch/
      become: yes

    - name: Copy config file 
      copy:
        src: elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        force: yes
      become: yes

    - name: Add Server Certificate
      blockinfile:
        dest: /etc/elasticsearch/elasticsearch.yml
        block: |
          node.name: {{ inventory_hostname }}
          xpack.security.transport.ssl.enabled: true
          xpack.security.transport.ssl.verification_mode: "certificate"
          xpack.security.transport.ssl.key: "/etc/elasticsearch/security/{{ inventory_hostname }}/{{ inventory_hostname }}.key"
          xpack.security.transport.ssl.certificate: "/etc/elasticsearch/security/{{ inventory_hostname }}/{{ inventory_hostname }}.crt"
          xpack.security.transport.ssl.certificate_authorities: "/etc/elasticsearch/security/ca/ca.crt"

          xpack.security.http.ssl.enabled: true
          xpack.security.http.ssl.key: "/etc/elasticsearch/security/{{ inventory_hostname }}/{{ inventory_hostname }}.key"
          xpack.security.http.ssl.certificate: "/etc/elasticsearch/security/{{ inventory_hostname }}/{{ inventory_hostname }}.crt"
          xpack.security.http.ssl.certificate_authorities: "/etc/elasticsearch/security/ca/ca.crt"
      become: yes

    - name: Copy role mapping
      copy:
        src: role_mapping.yml
        dest: /etc/elasticsearch/role_mapping.yml
        force: yes
      become: yes

    - name: Ensures /data/elasticsearch/data dir exists
      file: path=/data/elasticsearch/data state=directory owner=elasticsearch group=elasticsearch
      become: yes

    - name: Ensures /data/elasticsearch/logs dir exists
      file: path=/data/elasticsearch/logs state=directory owner=elasticsearch group=elasticsearch
      become: yes

    - name: Ensures /data/elasticsearch/backup dir exists
      file: path=/data/elasticsearch/backup state=directory owner=elasticsearch group=elasticsearch
      become: yes

    - name: daemon-reload
      command: systemctl daemon-reload
      become: yes

    - name: enable elasticsearch.service
      command: systemctl enable elasticsearch.service
      become: yes

    - name: start elasticsearch.service
      command: systemctl start elasticsearch.service
      become: yes