- name: Logstash Installation
  hosts: node3
  tasks:
    - name: Ensure logstash is at the latest version
      #apt: name=logstash=1:7.11.1-1 state=present
      apt: name=logstash=1:7.11.1-1 state=present
      become: yes
    
    - name: Ensures /etc/logstash/certs dir exists
      file: path=/etc/logstash/certs state=directory
      become: yes
    
    - name: Copy ca file
      copy:
        src: security/ca/ca.crt
        dest: /etc/logstash/certs/ca.crt
      become: yes

    - name: Copy config file
      copy:
        src: config/logstash.yml
        dest: /etc/logstash/logstash.yml
        force: yes
      become: yes    

    - name: Copy pipeline file
      copy:
        src: config/pipelines/file_input.conf
        dest: /etc/logstash/conf.d/file_input.conf
        force: yes
      become: yes

    - name: Copy pipeline file
      copy:
        src: config/pipelines/target.conf
        dest: /etc/logstash/conf.d/target.conf
        force: yes
      become: yes

    - name: Copy pipeline file
      copy:
        src: config/pipelines/master-data.conf
        dest: /etc/logstash/conf.d/master-data.conf
        force: yes
      become: yes

    
    - name: start logstash
      service:
          name: logstash
          state: restarted
      become: yes

