version: '3.6'

services:

  swag:
    image: linuxserver/swag
    container_name: nginx-docker_swag
    cap_add:
      - NET_ADMIN
    env_file: "configuration/${HOSTNAME}/.env-default"
    environment:
      # gitlab-runner uses standard id 999 - test it with id gitlab-runner
      # otherwise automatic pipeline will fail because the container
      # adjusts the ownership of the linked volumes
      - PUID=999
      - PGID=999
      - TZ=Africa/Kigali
      # - URL=dev.cndp.org.rw
      - VALIDATION=http
      # - SUBDOMAINS=crm,www
    #  - DNSPLUGIN=cloudflare #optional
    #  - PROPAGATION= #optional
    #  - DUCKDNSTOKEN= #optional
      - EMAIL= etienne.birara@risa.gov.rw
    #  - DHLEVEL=2048 #optional.
    #  - ONLY_SUBDOMAINS=false #optional
    #  - EXTRA_DOMAINS= #optional
      # - STAGING=true #optional
    volumes:
    # - ./swag/config:/config/nginx
    - ./swag/config/site-confs:/config/nginx/site-confs
    - ./swag/config/proxy-confs:/config/nginx/proxy-confs
    - ./swag/config/proxy.conf:/config/nginx/proxy.conf
    # - ./swag/config/nginx.conf:/config/nginx/nginx.conf
    # - ./swag/config/nginx.confbkp:/config/nginx/nginx.confbkp
    - ./swag/config/error-pages.conf:/config/nginx/error-pages.conf
    # - ./swag/static_sites/:/config/www
    networks:
      - infrastructure_default
    ports:
     - "443:443"
     - "80:80" #optional
    restart: always

networks:
  infrastructure_default: # external network
    external: true


