- name: Logstash Pipelines.yml Update
  hosts: node3
  tasks:

    - name: Copy pipelines yml
      copy:
        src: pipelines-{{ lookup('env','CI_COMMIT_BRANCH') }}.yml
        dest: /etc/logstash/pipelines.yml
        force: yes
      become: yes
