- name: Logstash Config Update and Restart
  hosts: node3
  tasks:

    - name: Copy logstash yml
      copy:
        src: ../logstash.yml
        dest: /etc/logstash/logstash.yml
        force: yes
      become: yes
    
    - name: stop logstash
      service:
          name: logstash
          state: stopped
      become: yes

    - name: start logstash
      service:
          name: logstash
          state: started
      become: yes