- name: Logstash Pipelines.yml Update
  hosts: node3
  tasks:

    - name: Copy pipelines yml
      copy:
        src: ../pipelines-{{ lookup('ENV','ENV') }}.yml
        dest: /etc/logstash/pipelines.yml
        force: yes
      become: yes
