- name: Logstash Installation
  hosts: node3
  tasks:
    - name: Ensure logstash is at "{{ lookup('ENV','LOGSTASH_VERSION') }}" version
      #apt: name=logstash=1:7.11.1-1 state=present
      apt: name=logstash={{ lookup('ENV','LOGSTASH_VERSION') }} state=present
      become: yes

    - name: Install Logstash filter JSON plugin
      logstash_plugin:
        state: present
        name: logstash-filter-json_encode
      become: yes

    - name: Install sentiment analyzer filter plugin
      logstash_plugin:
        state: present
        name: logstash-filter-sentimentalizer
      become: yes

    - name: Install extractnumbers filter plugin
      logstash_plugin:
        state: present
        name: logstash-filter-extractnumbers
      become: yes
    
    - name: Ensures /etc/logstash/security dir exists
      file: path=/etc/logstash/security state=directory
      become: yes
    
    - name: Copy Security Folder
      copy:
        src: ../security
        dest: /etc/logstash/
      become: yes

    - name: Copy config file
      copy:
        src: ../logstash.yml
        dest: /etc/logstash/logstash.yml
        force: yes
      become: yes

    - name: Ensures /etc/logstash/conf.d dir exists
      file: path=/etc/logstash/conf.d state=directory
      become: yes

    - name: Ensures /etc/logstash/templates dir exists
      file: path=/etc/logstash/templates state=directory
      become: yes

    - name: Copy pipeline yml
      copy:
        src: ../pipelines.yml
        dest: /etc/logstash/pipelines.yml
        force: yes
      become: yes
    
    - name: stop logstash
      service:
          name: logstash
          state: stopped
      become: yes

    - name: start logstash
      service:
          name: logstash
          state: started
      become: yes

    # - name: start logstash
    #   command: service logstash start
    #   become: yes


    # - name: start logstash
    #   service:
    #       name: logstash
    #       state: started
    #       arguments: --pipeline.unsafe_shutdown
    #   become: yes


    # - name: start logstash
    #   service:
    #       name: logstash
    #       state: restarted
    #   become: yes  
