- name: Logstash Pipeline Update & restart
  hosts: node3
  tasks:

    - name: Copy pipeline yml
      copy:
        src: ../pipelines.yml
        dest: /etc/logstash/pipelines.yml
        force: yes
      become: yes
    
    - name: start logstash
      service:
          name: logstash
          state: restarted
      become: yes  
