- name: Kibana Instalation
  hosts: node1
  tasks:
    - name: Ensure kibana is at the latest version
      apt: name=kibana state=latest
      become: yes
    - name: Ensures /etc/kibana/config/certs dir exists
      file: path=/etc/kibana/config/certs state=directory
      become: yes
    - name: Copy ca file 
      copy:
        src: security/staging/ca/ca.crt
        dest: /etc/kibana/config/certs/ca.crt
      become: yes
    - name: Copy config file 
      copy:
        src: kibana/staging/kibana-conf-stage.yml
        dest: /etc/kibana/kibana.yml
        force: yes
      become: yes
    - name: start kibana
      service:
          name: kibana
          state: restarted
      become: yes
