# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-kibana.html

- module: kibana
  xpack.enabled: true
  metricsets:
    - stats
  period: 10s
  hosts: ["$KIBANA_HOSTS"]
  #basepath: ""
  username: "$ELASTICSEARCH_USERNAME"
  password: "$ELASTICSEARCH_PASSWORD"
  ssl.certificate_authorities: ["/etc/metricbeat/security/ca/ca.crt"]
  ssl.enabled: true
