- name: Logstash Installation
  hosts: node3
  tasks:
    - name: Ensure logstash is at "{{ lookup('ENV','logstash_version') }}" version
      #apt: name=logstash=1:7.11.1-1 state=present
      apt: name=logstash={{ lookup('ENV','logstash_version') }} state=present
      become: yes
    
    - name: Ensures /etc/logstash/security dir exists
      file: path=/etc/logstash/security state=directory
      become: yes
    
    - name: Copy Security Folder
      copy:
        src: security
        dest: /etc/logstash/
      become: yes

    - name: Copy config file
      copy:
        src: logstash.yml
        dest: /etc/logstash/logstash.yml
        force: yes
      become: yes

    - name: Ensures /etc/logstash/conf.d dir exists
      file: path=/etc/logstash/conf.d state=directory
      become: yes

    - name: Copy pipeline yml
      copy:
        src: pipelines.yml
        dest: /etc/logstash/pipelines.yml
        force: yes
      become: yes

    - name: Copy pipeline folder
      copy:
        src: pipelines
        dest: /etc/logstash/
        force: yes
      become: yes
    
    - name: start logstash
      service:
          name: logstash
          state: restarted
      become: yes  
