# Default Stages

stages:
    - base_setup            # For setting up base requirements (one time run)
    - deploy_elk_stack      # For deploying different ELK modules/componenets
    - logstash_updates      # For updates to logstash.yml or pipelines.yml
    - maintenance           # For pulling logs into GIT
    - user_role_api         # For User and Role migration API
    - temp                  # For running temporary scripts for testing or other purposes

# OLD
# stages:
#     - env_setup
#     - deploy_role_user_migration
#     - deploy
#     - deploy_elasticsearch
#     - deploy_kibana
#     - deploy_logstash
#     - deploy_heartbeat
#     - deploy_metricbeat
#     - deploy_logstash_files
#     - maintenance
#     - restart_logstash
