# Default Stages

stages:
    - env_setup
    - deploy_elasticsearch
    - deploy_kibana
    - deploy_logstash
    - deploy_heartbeat
    - deploy_metricbeat
    - deploy_logstash_files
    - restart_logstash