# Default Stages

stages:
    - base_setup
    - deploy_elk_stack
    - logstash_updates
    - maintenance
    - user_role_api
    - temp

# OLD
# stages:
#     - env_setup
#     - deploy_role_user_migration
#     - deploy
#     - deploy_elasticsearch
#     - deploy_kibana
#     - deploy_logstash
#     - deploy_heartbeat
#     - deploy_metricbeat
#     - deploy_logstash_files
#     - maintenance
#     - restart_logstash
