# Default Stages

stages:
    - base_setup            # For setting up base requirements (one time run)
    - deploy_elk_stack      # For deploying different ELK modules/componenets
    - logstash_updates      # For updates to logstash.yml or pipelines.yml
    - restart_stack         # For restaring entire ELK stack (logstash, beats, kibana, elasticsearch)
    - stop_module           # For stopping individual module
    - start_module          # For starting incividual module
    - logs                  # For pulling logs into GIT
    - migration_api         # For User and Role migration API
    - ldap                  # For installing LDAP
    - testing               # For running temporary scripts for testing or other purposes

# OLD
# stages:
#     - env_setup
#     - deploy_role_user_migration
#     - deploy
#     - deploy_elasticsearch
#     - deploy_kibana
#     - deploy_logstash
#     - deploy_heartbeat
#     - deploy_metricbeat
#     - deploy_logstash_files
#     - maintenance
#     - restart_logstash
