# Default Stages

stages:
## Base environment setup
    - base_setup

## Deploy ELK stack modules
    - deploy_elk_stack

## Logstash updates - pipelines.yml / logstash data files
    - logstash_updates

## For logs and other maintenance jobs
    - maintenance
    
## User and Role API job
    - user_role_api

# OLD
# stages:
#     - env_setup
#     - deploy_role_user_migration
#     - deploy
#     - deploy_elasticsearch
#     - deploy_kibana
#     - deploy_logstash
#     - deploy_heartbeat
#     - deploy_metricbeat
#     - deploy_logstash_files
#     - maintenance
#     - restart_logstash
