# Rules

.rules_dev_auto:
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: on_success

.rules_dev_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: manual
    - when: never
  allow_failure: true

.rules_staging_auto:
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: on_success

.rules_staging_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
    - when: never
  allow_failure: true