# Rules Development

.rules_dev_auto:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: on_success

.rules_dev_auto_changes:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "development"'
      changes:
        - logstash/pipelines.yml
      when: on_success

.rules_dev_external:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_COMMIT_BRANCH == "development"'
      when: on_success

.rules_dev_manual:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: manual
    - when: never
  allow_failure: true

# Rules Staging

.rules_test_auto:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: on_success

.rules_test_manual:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
    - when: never
  allow_failure: true

.rules_test_auto_changes:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "staging"'
      changes:
        - logstash/pipelines.yml
      when: on_success