.rules_master:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

.rules_master_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
      
.rules_development:
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: on_success

.rules_development_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: manual

.rules_production:
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: on_success

.rules_production_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: manual

