# Templates

include:
  - local: '/gitlab-ci/templates/base-setup-templates.yml'
  - local: '/gitlab-ci/templates/elasticsearch-templates.yml'
  - local: '/gitlab-ci/templates/filebeat-templates.yml'
  - local: '/gitlab-ci/templates/heartbeat-templates.yml'
  - local: '/gitlab-ci/templates/kibana-templates.yml'
  - local: '/gitlab-ci/templates/ldap-templates.yml'
  - local: '/gitlab-ci/templates/logs-templates.yml'
  - local: '/gitlab-ci/templates/logstash-templates.yml'
  - local: '/gitlab-ci/templates/metricbeat-templates.yml'
  - local: '/gitlab-ci/templates/migration-templates.yml'
  - local: '/gitlab-ci/templates/restart-stack-templates.yml'
  - local: '/gitlab-ci/templates/start-module-templates.yml'
  - local: '/gitlab-ci/templates/stop-module-templates.yml'
  - local: '/gitlab-ci/templates/testing-templates.yml'