# Templates

.deploy_env_setup_template:
  stage: env_setup
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'ENVIRONMENT SETUP START'
         - bash -x environment_setup/env_setup.sh $NODE1 $NODE2 $NODE3 $ENV
         - echo 'ENVIRONMENT SETUP END'

.deploy_elasticsearch_template:
  stage: deploy_elasticsearch
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'ElasticSearch DEPLOY START'
         - ansible-playbook -i host elasticsearch/elasticsearch-setup.yml
         - echo 'ElasticSearch DEPLOY END'

.deploy_kibana_template:
  stage: deploy_kibana
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Prepare Variables START'
         - envsubst < "kibana/kibana.yml" > kibana_var.yml
         - cp kibana_var.yml kibana/kibana.yml
         - echo 'Prepare Variables END'
         - echo 'Kibana DEPLOY START'
         - ansible-playbook -i host kibana/kibana-setup.yml
         - echo 'Kibana DEPLOY END'

.deploy_logstash_template:
  stage: deploy_logstash
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Logstash DEPLOY START'
         - ansible-playbook -i host logstash/logstash-setup.yml
         - echo 'Logstash DEPLOY END'

.deploy_heartbeat_template:
  stage: deploy_heartbeat
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Prepare Variables START'

         - echo 'Heartbeat.yml'
         - envsubst < "heartbeat/heartbeat.yml" > heartbeat_var.yml
         - cp heartbeat_var.yml heartbeat/heartbeat.yml

         - echo '--- Monitors - Elastic DEV ---'
         - envsubst < "heartbeat/monitors.d/elastic-dev-gcc.yml" > elastic-dev-gcc_var.yml
         - cp elastic-dev-gcc_var.yml heartbeat/monitors.d/elastic-dev-gcc.yml

         - echo '--- Monitors - Elastic STAGE ---'
         - envsubst < "heartbeat/monitors.d/elastic-staging-gcc.yml" > elastic-staging-gcc_var.yml
         - cp elastic-staging-gcc_var.yml heartbeat/monitors.d/elastic-staging-gcc.yml

         - echo '--- Monitors - Kibana DEV ---'
         - envsubst < "heartbeat/monitors.d/kibana-dev-gcc.yml" > kibana-dev-gcc_var.yml
         - cp kibana-dev-gcc_var.yml heartbeat/monitors.d/kibana-dev-gcc.yml

         - echo '--- Monitors - Kibana STAGE ---'
         - envsubst < "heartbeat/monitors.d/kibana-staging-gcc.yml" > kibana-staging-gcc_var.yml
         - cp kibana-staging-gcc_var.yml heartbeat/monitors.d/kibana-staging-gcc.yml
         
         - echo 'Prepare Variables END'
         - echo 'Heartbeat DEPLOY START'
         - ansible-playbook -i host heartbeat/heartbeat-setup.yml
         - echo 'Heartbeat DEPLOY END'

.deploy_test_template:
  stage: test
  script:
         - export