# Templates

.deploy_env_setup_template:
  stage: env_setup
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'ENVIRONMENT SETUP START'
         - bash -x environment_setup/env_setup.sh $NODE1 $NODE2 $NODE3 $ENV
         - echo 'ENVIRONMENT SETUP END'

.deploy_elasticsearch_template:
  stage: deploy_elasticsearch
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'ElasticSearch DEPLOY START'
         - ansible-playbook -i host elasticsearch/elasticsearch-setup.yml
         - echo 'ElasticSearch DEPLOY END'

.deploy_kibana_template:
  stage: deploy_kibana
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Prepare Variables START'
         - envsubst < "kibana/kibana.yml" > kibana_var.yml
         - cp kibana_var.yml kibana/kibana.yml
         - echo 'Prepare Variables END'
         - echo 'Kibana DEPLOY START'
         - ansible-playbook -i host kibana/kibana-setup.yml
         - echo 'Kibana DEPLOY END'

.deploy_logstash_template:
  stage: deploy_logstash
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Prepare Variables START'
         
         - echo 'PIPELINE kpi_data.conf'
         - envsubst < "logstash/pipelines/kpi_data.conf" > kpi_data_var.conf
         - cp kpi_data_var.conf logstash/pipelines/kpi_data.conf

         - echo 'PIPELINE master-data.conf'
         - envsubst < "logstash/pipelines/master-data.conf" > master-data_var.conf
         - cp master-data_var.conf logstash/pipelines/master-data.conf

         - echo 'PIPELINE target.conf'
         - envsubst < "logstash/pipelines/target.conf" > target_var.conf
         - cp target_var.conf logstash/pipelines/target.conf

         - echo 'Prepare Variables END'
         - echo 'Logstash DEPLOY START'
         - ansible-playbook -i host logstash/logstash-setup.yml
         - echo 'Logstash DEPLOY END'

.deploy_heartbeat_template:
  stage: deploy_heartbeat
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Prepare Variables START'

         - echo 'Heartbeat.yml'
         - envsubst < "heartbeat/heartbeat.yml" > heartbeat_var.yml
         - cp heartbeat_var.yml heartbeat/heartbeat.yml

         - echo '--- Monitors - Elastic DEV ---'
         - envsubst < "heartbeat/monitors.d/elastic-dev-gcc.yml" > elastic-dev-gcc_var.yml
         - cp elastic-dev-gcc_var.yml heartbeat/monitors.d/elastic-dev-gcc.yml

         - echo '--- Monitors - Elastic STAGE ---'
         - envsubst < "heartbeat/monitors.d/elastic-staging-gcc.yml" > elastic-staging-gcc_var.yml
         - cp elastic-staging-gcc_var.yml heartbeat/monitors.d/elastic-staging-gcc.yml

         - echo '--- Monitors - Kibana DEV ---'
         - envsubst < "heartbeat/monitors.d/kibana-dev-gcc.yml" > kibana-dev-gcc_var.yml
         - cp kibana-dev-gcc_var.yml heartbeat/monitors.d/kibana-dev-gcc.yml

         - echo '--- Monitors - Kibana STAGE ---'
         - envsubst < "heartbeat/monitors.d/kibana-staging-gcc.yml" > kibana-staging-gcc_var.yml
         - cp kibana-staging-gcc_var.yml heartbeat/monitors.d/kibana-staging-gcc.yml
         
         - echo 'Prepare Variables END'
         - echo 'Heartbeat DEPLOY START'
         - ansible-playbook -i host heartbeat/heartbeat-setup.yml
         - echo 'Heartbeat DEPLOY END'

.deploy_metricbeat_template:
  stage: deploy_metricbeat
  script:
         - echo $ENV
         - echo $NODE1
         - echo $NODE2
         - echo $NODE3
         - echo 'Prepare Variables START'

         - echo 'Metricbeat.yml'
         - envsubst < "metricbeat/metricbeat.yml" > metricbeat_var.yml
         - cp metricbeat_var.yml metricbeat/metricbeat.yml

         - echo '--- Modules - ElasticSearch X-Pack ---'
         - envsubst < "metricbeat/modules.d/elasticsearch-xpack.yml" > elasticsearch-xpack_var.yml
         - cp elasticsearch-xpack_var.yml metricbeat/modules.d/elasticsearch-xpack.yml

         - echo '--- Modules - ElasticSearch ---'
         - envsubst < "metricbeat/modules.d/elasticsearch.yml" > elasticsearch-m_var.yml
         - cp elasticsearch-m_var.yml metricbeat/modules.d/elasticsearch.yml
        
         - echo '--- Modules - Kibana X-Pack ---'
         - envsubst < "metricbeat/modules.d/kibana-xpack.yml" > kibana-xpack_var.yml
         - cp kibana-xpack_var.yml metricbeat/modules.d/kibana-xpack.yml

         - echo '--- Modules - Kibana ---'
         - envsubst < "metricbeat/modules.d/kibana.yml" > kibana-m_var.yml
         - cp kibana-m_var.yml metricbeat/modules.d/kibana.yml

         - echo '--- Modules - System ---'
         - envsubst < "metricbeat/modules.d/system.yml" > system_var.yml
         - cp system_var.yml metricbeat/modules.d/system.yml

         - echo 'Prepare Variables END'
         - echo 'Metricbeat DEPLOY START'
         - ansible-playbook -i host metricbeat/metricbeat-setup.yml
         - echo 'Metricbeat DEPLOY END'
