# Templates

include:
  - local: '/gitlab-ci/templates/base-setup-templates.yml'
  - local: '/gitlab-ci/templates/elasticsearch-templates.yml'
  - local: '/gitlab-ci/templates/heartbeat-templates.yml'
  - local: '/gitlab-ci/templates/kibana-templates.yml'
  - local: '/gitlab-ci/templates/logs-templates.yml'
  - local: '/gitlab-ci/templates/logstash-templates.yml'
  - local: '/gitlab-ci/templates/metricbeat-templates.yml'
  - local: '/gitlab-ci/templates/user-role-api-templates.yml'
  - local: '/gitlab-ci/templates/temp-templates.yml'