# Variables

.variables_general:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    HOSTS: "node1, node2, node3"
    ELASTICSEARCH_HOSTS: https://node1:9200", "https://node2:9200", "https://node3:9200
    KIBANA_XPACK_ENCRYPTIONKEY: "BDHcisme3231234msid8493029384930281hc"
    KIBANA_HOSTS: https://node1:5601", "https://node2:5601
    KIBANA_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "BDHcisme3231234msid8493029384930281hc"
    LDAP_URL: "https://apachemirror.wuchna.com//directory/apacheds/dist/2.0.0.AM26/apacheds-2.0.0.AM26-amd64.deb"
    LDAP_FILE: "apacheds-2.0.0.AM26-amd64.deb"
    LDAP_SERVICE: "apacheds-2.0.0.AM26-default"


.variables_dev:
  extends:
    .variables_general
  environment:
    name: dev
  tags:
    - dev
  variables:
    NODE1: $NODE1_DEV
    NODE2: $NODE2_DEV
    NODE3: $NODE3_DEV
    ENV: DEV
    ELK_VERSION: "7.13.3"
    LOGSTASH_VERSION: "1:7.13.3-1"
    ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD_DEV
    ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME_DEV
    KIBANA_URL: $KIBANA_URL_DEV
    ELASTICSEARCH_URL: $ELASTICSEARCH_URL_DEV


.variables_test:
  extends:
    .variables_general
  environment:
    name: test
  tags:
    - test
  variables:
    NODE1: $NODE1_TEST
    NODE2: $NODE2_TEST
    NODE3: $NODE3_TEST
    ENV: TEST
    ELK_VERSION: "7.12.1"
    LOGSTASH_VERSION: "1:7.12.1-1"
    ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD_TEST
    ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME_TEST
    ELASTICSEARCH_URL: $ELASTICSEARCH_URL_TEST
    KIBANA_URL: $KIBANA_URL_TEST

    #Migration - DEV to TEST
    
    ENABLE_ROLE: "true"
    NO_OF_ROLES_USER_MIGRATE: "ALL"
    ENABLE_USER: "true"
    ENABLE_OBJECT: "true"
    ENABLE_SPACE: "true"
    OBJECT_SOURCE: "https://$NODE1_DEV:5601/s/"
    OBJECT_DEST: "https://$NODE1_TEST:5601/s/"
    #OBJECT_TYPE: "index-pattern,visualization,dashboard,lens,search,config,canvas-workpad,url,map,tag,query,graph-workspace,canvas-element,infrastructure-ui-source,metrics-explorer-view,inventory-view,apm-indices"
    OBJECT_TYPE: "dashboard,search,index-pattern,url,visualization,lens,config,query,canvas-element,canvas-workpad,graph-workspace,tag,map,infrastructure-ui-source,metrics-explorer-view,inventory-view,apm-indices"
    PROPERTY_FILE: "application-dev"
    ROLE_SOURCE: "https://$KIBANA_URL_DEV/api/security/role?pretty"
    ROLE_DEST: "https://$KIBANA_URL_TEST/api/security/role/"
    SPACE_ID: "national-application--government-command-center"
    SPACE_SOURCE: "https://$KIBANA_URL_DEV/api/spaces/space"
    SPACE_DEST: "https://$KIBANA_URL_TEST/api/spaces/space"
    USER_SOURCE: "https://$ELASTICSEARCH_URL_DEV/_security/user?pretty"
    USER_DEST: "https://$ELASTICSEARCH_URL_TEST/_security/user/"



.variables_prod:
  extends:
    .variables_general
  environment:
    name: prod
  tags:
    - prod
  variables:
    NODE1: $NODE1_PROD
    NODE2: $NODE2_PROD
    NODE3: $NODE3_PROD
    ENV: PROD
    ELK_VERSION: "7.12.1"
    LOGSTASH_VERSION: "1:7.12.1-1"
    ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD_PROD
    ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME_PROD
    ELASTICSEARCH_URL: $ELASTICSEARCH_URL_PROD
    KIBANA_URL: $KIBANA_URL_PROD
    
    #Migration - TEST to PROD
    
    ENABLE_ROLE: "true"
    NO_OF_ROLES_USER_MIGRATE: "ALL"
    ENABLE_USER: "true"
    ENABLE_OBJECT: "true"
    ENABLE_SPACE: "true"
    OBJECT_SOURCE: "https://$NODE1_TEST:5601/s/"
    OBJECT_DEST: "https://$NODE1_PROD:5601/s/"
    #OBJECT_TYPE: "index-pattern,visualization,dashboard,lens,search,config,canvas-workpad,url,map,tag,query,graph-workspace,canvas-element,infrastructure-ui-source,metrics-explorer-view,inventory-view,apm-indices"
    OBJECT_TYPE: "dashboard,search,index-pattern,url,visualization,lens,config,query,canvas-element,canvas-workpad,graph-workspace,tag,map,infrastructure-ui-source,metrics-explorer-view,inventory-view,apm-indices"
    PROPERTY_FILE: "application-dev"
    ROLE_SOURCE: "https://$KIBANA_URL_TEST/api/security/role?pretty"
    ROLE_DEST: "https://$KIBANA_URL_PROD/api/security/role/"
    SPACE_ID: "national-application--government-command-center"
    SPACE_SOURCE: "https://$KIBANA_URL_TEST/api/spaces/space"
    SPACE_DEST: "https://$KIBANA_URL_PROD/api/spaces/space"
    USER_SOURCE: "https://$ELASTICSEARCH_URL_TEST/_security/user?pretty"
    USER_DEST: "https://$ELASTICSEARCH_URL_PROD/_security/user/"




# .variables_general:
#   variables:
#     GIT_SUBMODULE_STRATEGY: recursive
#     elk_version: "7.12.1" # can vary in different environments
#     logstash_version: "1:7.12.1-1"
#     hosts: "node1, node2, node3"
#     elasticsearch_hosts: https://node1:9200", "https://node2:9200", "https://node3:9200 # can vary in different environments
#     kibana_xpack_encryptionKey: "BDHcisme3231234msid8493029384930281hc" # can vary in different environments
#     kibana_hosts: https://node1:5601", "https://node2:5601 # can vary in different environments
#     kibana_encryptedSavedObjects_encryptionKey: "BDHcisme3231234msid8493029384930281hc" # can vary in different environments

# .variables_dev:
#   extends:
#     .variables_general
#   environment:
#     name: development # please rename to dev while refactoring
#   tags:
#     - dev
#   variables:
#     elasticsearch_password: $elasticsearch_password_dev
#     elasticsearch_username: $elasticsearch_username_dev
#     kibana_url: "https://kibana.dev.gcc.gov.rw"
#     elasticsearch_url: "https://elasticsearch.dev.gcc.gov.rw:443"

# .variables_test: # please rename to .variables_test while refactoring
#   extends:
#     .variables_general
#   environment:
#     name: staging # please rename to test while refactoring
#   tags:
#     - staging # please rename to test while refactoring
#   variables:
#     elasticsearch_password: $elasticsearch_password_test
#     elasticsearch_username: $elasticsearch_username_test
#     elasticsearch_url: "https://gbis-elastic.staging.risa.gov.rw:443"
#     kibana_url: "https://gbis.staging.risa.gov.rw"